
package view.book;

/**
 *
 * @author Sterbenxy13
 */
public class FrBookManagerANTIGO extends javax.swing.JFrame {
    private final controller.BookManager manager;
    private final java.awt.Frame parent;
    
    /**
     * Creates new form FrBookManager
     */
    public FrBookManagerANTIGO(java.awt.Frame parent) {
        initComponents();
        manager = new controller.BookManager();
        this.parent = parent;
        
        this.panData.setManager(this.manager);
        this.panData.updateData();
        this.setVisible(true);
        
        this.blockNotAllowedButtons();
    }
    
    private void blockNotAllowedButtons() {
        if (this.panData.isEmpty()) {
            this.btnEdit.setEnabled(false);
            this.btnRemove.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panData = new view.components.PanData();
        panOptions = new javax.swing.JPanel();
        btnCancel = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        lblTitle1 = new view.components.LblTitle();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 400));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        panOptions.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 10));

        btnCancel.setText("Voltar");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        panOptions.add(btnCancel);

        btnAdd.setText("Adicionar");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        panOptions.add(btnAdd);

        btnEdit.setText("Editar");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        panOptions.add(btnEdit);

        btnRemove.setText("Remover");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });
        panOptions.add(btnRemove);

        lblTitle1.setText("Gerenciado de livros");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTitle1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panOptions, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panData, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panOptions, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.parent.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        view.book.FrBookRegisterANTIGO registerWindow
        = new view.book.FrBookRegisterANTIGO(this, true, this.manager);
        registerWindow.setVisible(true);

        this.panData.updateData();
        this.blockNotAllowedButtons();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        view.components.FrSelect selectWindow
        = new view.components.FrSelect(this, true, this.manager);
        selectWindow.setVisible(true);

        if (!selectWindow.wasSelected()) {
            return;
        } 
        
        int index = selectWindow.getEdtIndexValue();
        view.book.FrBookEditANTIGO editWindow
        = new view.book.FrBookEditANTIGO(this, true, this.manager, index);
        editWindow.setVisible(true);

        this.panData.updateData();
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        view.components.FrSelect removeWindow
            = new view.components.FrSelect(this, true, this.manager);
        removeWindow.setVisible(true);

        if (!removeWindow.wasSelected()) {
            return;
        } 
        
        int index = removeWindow.getEdtIndexValue();
        view.components.PanData temp = new view.components.PanData();
        temp.setManager(this.manager);
        temp.updateData(index);

        view.components.DlgConfirm confirmationDialog
            = new view.components.DlgConfirm(
            this,
            true,
            "Deseja remover este livro?",
            temp
        );
        confirmationDialog.setVisible(true);

        if (confirmationDialog.getCorfirmation()) {
            this.manager.remove(index);
            new view.components.DlgAlert(this, true, "Livro removido com sucesso!");
        }
        this.panData.updateData();
        this.blockNotAllowedButtons();

    }//GEN-LAST:event_btnRemoveActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.parent.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnRemove;
    private view.components.LblTitle lblTitle1;
    private view.components.PanData panData;
    private javax.swing.JPanel panOptions;
    // End of variables declaration//GEN-END:variables
}
