
package view.book.components;

/**
 *
 * @author Sterbenxy13
 */
public class FrAuthor extends javax.swing.JDialog {
    private javax.swing.DefaultListModel<model.entity.Author> listModel;
    
    /**
     * Creates new form FrGenre
     */
    public FrAuthor(java.awt.Dialog parent, boolean modal, java.util.List<model.entity.Author> authors) {
        super(parent, modal);
        initComponents();
        listModel = new javax.swing.DefaultListModel<>();
        for (model.entity.Author a: authors) {
            listModel.addElement(a);
        }
        lstAuthor.setModel(listModel);
    }
    
    public java.util.List<model.entity.Author> getAuthorValues() {
        java.util.List<model.entity.Author> result = new java.util.ArrayList<>();
        for (int i = 0; i < this.listModel.size(); i ++) {
            result.add(
                    listModel.getElementAt(i)
            );
        }
        return result;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new view.components.LblTitle();
        lblAlert = new view.components.LblAlert();
        panAuthor = new javax.swing.JScrollPane();
        lstAuthor = new javax.swing.JList<>();
        panOptions = new javax.swing.JPanel();
        btnCancel = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitle.setText("Autores");

        lstAuthor.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        panAuthor.setViewportView(lstAuthor);

        btnCancel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnCancel.setText("Voltar");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        panOptions.add(btnCancel);

        btnAdd.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnAdd.setText("Adicionar");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        panOptions.add(btnAdd);

        btnRemove.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnRemove.setText("Remover");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });
        panOptions.add(btnRemove);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panOptions, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addComponent(panAuthor, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAlert, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAlert, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panAuthor, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panOptions, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        view.components.DlgTextInput edtAuthor = new view.components.DlgTextInput(this, true, "Nome do autor");
        edtAuthor.setVisible(true);
        view.components.DlgTextInput edtHomeTown = new view.components.DlgTextInput(this, true, "Cidade natal do autor");
        edtHomeTown.setVisible(true);        
        
        lblAlert.setText("");
        listModel.addElement(
                new model.entity.Author(edtAuthor.getValue(), edtHomeTown.getValue())
        );
        lstAuthor.setModel(listModel);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        if (lstAuthor.getSelectedIndex() != -1) {
            listModel.remove(lstAuthor.getSelectedIndex());
            lblAlert.setText("Removido com sucesso!");
        } else {
            lblAlert.setText("Selecione um item para remover!");
        }
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnRemove;
    private view.components.LblAlert lblAlert;
    private view.components.LblTitle lblTitle;
    private javax.swing.JList<model.entity.Author> lstAuthor;
    private javax.swing.JScrollPane panAuthor;
    private javax.swing.JPanel panOptions;
    // End of variables declaration//GEN-END:variables
}
