
package view.book.components;

/**
 *
 * @author Sterbenxy13
 */
public class PanBookDataInsertion extends javax.swing.JPanel {
    private java.awt.Dialog parent;
    private java.util.List<model.entity.Author> authors
            = new java.util.ArrayList<>();
    private java.util.List<String> genres
            = new java.util.ArrayList<>();
    
    /**
     * Creates new form PanBookData
     */
    public PanBookDataInsertion() {
        initComponents();
    }
    
    public void setParent(java.awt.Dialog parent) {
        this.parent = parent;
    }
    
    public void setValues(String jsonData) {
        model.entity.Book temp = model.persistence.JSONService.fromJson(jsonData, model.entity.Book.class).get(0);
        this.setTitleValue(temp.getTitle());
        this.setPublishYearValue(temp.getPublishYear());
        genres = temp.getGenres();
        this.setGenresValue(genres);
        authors = temp.getAuthors();
        this.setAuthorsValue(authors);
    }

    public String getTitleValue() {
        return this.edtTitle.getText();
    }
    
    public Integer getPublishYearValue() {
        if (this.edtPublishYear.getText().equals("")) {
            return -1;
        }
        return Integer.valueOf(this.edtPublishYear.getText());
    }
    
    public java.util.List<String> getGenresValue() {
        return this.genres;
    }
    
    public java.util.List<model.entity.Author> getAuthorsValue() {
        return this.authors;
    }
    
    public void setTitleValue(String title) {
        this.edtTitle.setText(title);
    }
    
    public void setPublishYearValue(Integer publishYear) {
        this.edtPublishYear.setValue(publishYear);
    }
    
    public void setGenresValue(java.util.List<String> genres) {
        this.genres = genres;
    }
    
    public void setAuthorsValue(java.util.List<model.entity.Author> authors) {
        this.authors = authors;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        edtTitle = new javax.swing.JTextField();
        lblPublishYear = new javax.swing.JLabel();
        edtPublishYear = new javax.swing.JFormattedTextField();
        lblGenres = new javax.swing.JLabel();
        btnViewGenres = new javax.swing.JButton();
        lblAuthors = new javax.swing.JLabel();
        btnViewAuthors = new javax.swing.JButton();

        lblTitle.setText("Título:");

        edtTitle.setToolTipText("Título");

        lblPublishYear.setText("Ano de publicação:");

        edtPublishYear.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("####"))));
        edtPublishYear.setToolTipText("");

        lblGenres.setText("Gêneros:");

        btnViewGenres.setText("Expandir");
        btnViewGenres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewGenresActionPerformed(evt);
            }
        });

        lblAuthors.setText("Autores: ");

        btnViewAuthors.setText("Expandir");
        btnViewAuthors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAuthorsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle)
                    .addComponent(lblPublishYear)
                    .addComponent(lblGenres)
                    .addComponent(lblAuthors))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edtTitle)
                    .addComponent(edtPublishYear)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnViewGenres)
                            .addComponent(btnViewAuthors))
                        .addGap(0, 170, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtPublishYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPublishYear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewGenres)
                    .addComponent(lblGenres))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewAuthors)
                    .addComponent(lblAuthors))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewGenresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewGenresActionPerformed
        view.components.FrGenre edtGenre 
                = new view.components.FrGenre(this.parent, true, this.genres);
        edtGenre.setVisible(true);
        this.genres = edtGenre.getGenreValues();
    }//GEN-LAST:event_btnViewGenresActionPerformed

    private void btnViewAuthorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAuthorsActionPerformed
        view.book.components.FrAuthor edtAuthor = new view.book.components.FrAuthor(this.parent, true, this.authors);
        edtAuthor.setVisible(true);
        this.authors = edtAuthor.getAuthorValues();
    }//GEN-LAST:event_btnViewAuthorsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnViewAuthors;
    private javax.swing.JButton btnViewGenres;
    private javax.swing.JFormattedTextField edtPublishYear;
    private javax.swing.JTextField edtTitle;
    private javax.swing.JLabel lblAuthors;
    private javax.swing.JLabel lblGenres;
    private javax.swing.JLabel lblPublishYear;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
