
package view;

import controller.globals.Contexts;
import controller.viewController.TokenViewLoading;
import javax.swing.JFrame;
import view.dialogs.AbstractDialog;
import view.tokens.TokenViewResponse;

/**
 *
 * @author Sterbenxy13
 */
public class DlgMenuSelect extends AbstractDialog {
    private TokenViewResponse response;
    
    /**
     * Diálogo para seleção de menus.
     */
    public DlgMenuSelect(JFrame parent) {
        super(parent, true);
        initComponents();
        this.setTitle("Loren Library");
        this.response = new TokenViewResponse(Contexts.START);
    }
    
    @Override
    public TokenViewResponse getResponse() {
        return this.response;
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panOptions = new javax.swing.JPanel();
        btnUsers = new javax.swing.JButton();
        btnBooks = new javax.swing.JButton();
        btnLibrary = new javax.swing.JButton();
        lblTitle1 = new view.components.LblTitle();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        btnUsers.setText("Menu de usuários");
        btnUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsersActionPerformed(evt);
            }
        });
        panOptions.add(btnUsers);

        btnBooks.setText("Menu de livros");
        btnBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBooksActionPerformed(evt);
            }
        });
        panOptions.add(btnBooks);

        btnLibrary.setText("Biblioteca");
        btnLibrary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLibraryActionPerformed(evt);
            }
        });
        panOptions.add(btnLibrary);

        lblTitle1.setText("Menu principal");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTitle1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panOptions, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panOptions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsersActionPerformed
        this.response.setOrigin("USER");
        this.dispose();
    }//GEN-LAST:event_btnUsersActionPerformed

    private void btnBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBooksActionPerformed
        this.response.setOrigin("BOOK");
        this.dispose();
    }//GEN-LAST:event_btnBooksActionPerformed

    private void btnLibraryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLibraryActionPerformed
        this.response.setOrigin("LIBRARY");
        System.out.println("LIBRARY ACCESS DENIED");
    }//GEN-LAST:event_btnLibraryActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.response.setOrigin("EXIT");
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBooks;
    private javax.swing.JButton btnLibrary;
    private javax.swing.JButton btnUsers;
    private view.components.LblTitle lblTitle1;
    private javax.swing.JPanel panOptions;
    // End of variables declaration//GEN-END:variables
}
