
package view.user.components;

/**
 *
 * @author Sterbenxy13
 */
public class PanSelectUser extends javax.swing.JPanel {

    /**
     * Creates new form PanSelecionarPessoa
     */
    public PanSelectUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panIndex = new javax.swing.JPanel();
        lblIndex = new javax.swing.JLabel();
        edtIndex = new javax.swing.JSpinner();
        panDadosPessoa = new javax.swing.JScrollPane();
        edtDadosPessoa = new javax.swing.JTextArea();

        panIndex.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING, 30, 5));

        lblIndex.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblIndex.setText("ID:");
        panIndex.add(lblIndex);

        edtIndex.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        edtIndex.setMinimumSize(new java.awt.Dimension(100, 20));
        edtIndex.setPreferredSize(new java.awt.Dimension(100, 20));
        edtIndex.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                edtIndexStateChanged(evt);
            }
        });
        panIndex.add(edtIndex);

        edtDadosPessoa.setEditable(false);
        edtDadosPessoa.setColumns(20);
        edtDadosPessoa.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        edtDadosPessoa.setRows(5);
        panDadosPessoa.setViewportView(edtDadosPessoa);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panIndex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panDadosPessoa, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(panIndex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(panDadosPessoa, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    public void updateEdtIndexModel() {
//        edtIndex.setModel(new javax.swing.SpinnerNumberModel(
//                0, 
//                0, 
//                controllers.UserManager.getSize() - 1, ;
//                1
//            )
//        );
    }
    
    public int getEdtIndexValue(){
        return Integer.parseInt(edtIndex.getValue().toString());
    }
    
    private void edtIndexStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_edtIndexStateChanged
//        edtDadosPessoa.setText(
//            controllers.UserManager.getFormattedData(Integer.parseInt(edtIndex.getValue().toString()))
//        );
    }//GEN-LAST:event_edtIndexStateChanged
        
    public void atualizaDados() {
//        edtIndex.setModel(new javax.swing.SpinnerNumberModel(
//                Integer.parseInt(edtIndex.getValue().toString()), 
//                0, 
//                controllers.UserManager.getSize() - 1, 
//                1
//            )
//        );        
//        edtDadosPessoa.setText(
//            controllers.UserManager.getFormattedData(Integer.parseInt(edtIndex.getValue().toString()))
//        );
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea edtDadosPessoa;
    private javax.swing.JSpinner edtIndex;
    private javax.swing.JLabel lblIndex;
    private javax.swing.JScrollPane panDadosPessoa;
    private javax.swing.JPanel panIndex;
    // End of variables declaration//GEN-END:variables
}
