
package view.user.components;

/**
 *
 * @author Sterbenxy13
 */
public class PanUserDataInsertion extends javax.swing.JPanel {
    private java.awt.Dialog parent;
    private java.util.List<String> genres
            = new java.util.ArrayList<>();
    private java.util.List<model.entity.Book> readedBooks
            = new java.util.ArrayList<>();
    private controller.IEntityController manager;
    
    /**
     * Creates new form PanUserData
     */
    public PanUserDataInsertion() {
        initComponents();
    }

    public void setParent(java.awt.Dialog parent) {
        this.parent = parent;
    }
    
    public void setManager(controller.IEntityController manager) {
        this.manager = manager;
    }
    
    public void setValues(String jsonData) {
        model.entity.User temp = model.persistence.JSONService.fromJson(jsonData, model.entity.User.class).get(0);
        this.setNameValue(temp.getName());
        genres = temp.getFavoriteGenres();
        this.setGenresValue(genres);
        readedBooks = temp.getReadedBooks();
        this.setReadedBooksValue(readedBooks);
    } 
    
    public String getNameValue() {
        return this.edtName.getText();
    }
    
    public java.util.List<String> getGenresValue() {
        return this.genres;
    }
    
    public java.util.List<model.entity.Book> getReadedBooksValue() {
        return this.readedBooks;
    }
    
    public void setNameValue(String name) {
        this.edtName.setText(name);
    }

    public void setGenresValue(java.util.List<String> genres) {
        this.genres = genres;
    }

    public void setReadedBooksValue(java.util.List<model.entity.Book> readedBooks) {
        this.readedBooks = readedBooks;
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        edtName = new javax.swing.JTextField();
        lblGenres = new javax.swing.JLabel();
        btnViewGenre = new javax.swing.JButton();

        lblName.setText("Nome:");

        edtName.setText("Nome");

        lblGenres.setText("Gêneros favoritos:");

        btnViewGenre.setText("Expandir");
        btnViewGenre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewGenreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(lblName)
                        .addGap(77, 77, 77))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblGenres)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edtName)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnViewGenre)
                        .addGap(0, 134, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(edtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewGenre)
                    .addComponent(lblGenres))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewGenreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewGenreActionPerformed
        view.components.FrGenre edtGenre 
                = new view.components.FrGenre(this.parent, true, genres);
        edtGenre.setVisible(true);
        this.genres = edtGenre.getGenreValues();
    }//GEN-LAST:event_btnViewGenreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnViewGenre;
    private javax.swing.JTextField edtName;
    private javax.swing.JLabel lblGenres;
    private javax.swing.JLabel lblName;
    // End of variables declaration//GEN-END:variables
}
