
package view.components.dataForm;

import controller.viewController.EntityData;
import java.awt.Component;
import java.awt.Dimension;
import java.lang.reflect.Field;
import java.util.ArrayList;
import java.util.Dictionary;
import java.util.List;
import javax.swing.Box;
import javax.swing.BoxLayout;

/**
 *
 * @author Sterbenxy13
 */
public class PanDataForm<FI extends Component & FormInput> extends javax.swing.JPanel {
    private List<FI> formInputs;
    
    /**
     * Creates new form PanDataForm
     */
    public PanDataForm() {
        initComponents();
        this.formInputs = new ArrayList<>();
    }
    
    public void setFields(EntityData data) {
        this.formInputs.clear();
        for (String label: data.getLabels()) {             
            FI input = (FI) new PanStringFormInput(label);
            formInputs.add(input);
        }
        this.updateFormLayout();
    }
    
    private void updateFormLayout() {

        BoxLayout layout = new BoxLayout(this, BoxLayout.Y_AXIS);
        this.setLayout(layout);
        
        for (Component c: this.formInputs) {
            this.add(c);
            this.add(Box.createRigidArea(new Dimension(0, 2)));
        }
    }
    
    public EntityData getFormData() {
        EntityData data = new EntityData();
        
        for (FormInput i: this.formInputs) {
            data.put(i.getLabelValue(), i.getInputValue());
        }
        
        return data;
    }
    
    public void setFormData(EntityData data) {
        for (FormInput i: this.formInputs) {
            i.setInputValue((String) data.get(i.getLabelValue()));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
