
package view.components.dataForm;

/**
 * 
 * @author Sterbenxy13
 * @see view.components.dataForm.PanStringFormInput
 */
@Deprecated
public class PanListFormInput extends javax.swing.JPanel {// implements FormInput {

    private javax.swing.JTextField tempTextField;
    
    /**
     * Creates new form PanListFormInput
     */
    public PanListFormInput(String fieldName) {
        initComponents();
        this.label.setText(fieldName);
        this.tempTextField = new javax.swing.JTextField("N");
    }
    
//    @Override
//    public String getLabelValue() {
//        return this.label.getText();
//    }
//
//    @Override
//    public String getInputValue() {
//        return this.tempTextField.getText();
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        label.setText("None");

        jLabel1.setText("NÃO IMPLEMENTADA A LISTA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(55, 55, 55)
                .addComponent(jLabel1)
                .addGap(190, 190, 190))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label)
                    .addComponent(jLabel1))
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel label;
    // End of variables declaration//GEN-END:variables
}
