
package view.components.dataForm;

/**
 *
 * @author Sterbenxy13
 */
public class PanStringFormInput extends javax.swing.JPanel implements FormInput {

    /**
     * Creates new form PanStringFormInput
     */
    public PanStringFormInput(String fieldName) {
        initComponents();
        this.label.setText(fieldName);
        this.textField.setText(fieldName);
    }

    @Override
    public String getLabelValue() {
        return this.label.getText();
    }

    @Override
    public String getInputValue() {
        return this.textField.getText();
    }
    
    @Override
    public void setInputValue(String inputValue) {
        this.textField.setText(inputValue);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label = new javax.swing.JLabel();
        textField = new javax.swing.JTextField();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label.setLabelFor(textField);
        label.setText("None");
        label.setMinimumSize(new java.awt.Dimension(60, 16));
        label.setPreferredSize(new java.awt.Dimension(40, 16));
        add(label);

        textField.setText("None");
        textField.setAlignmentX(0.0F);
        textField.setMaximumSize(new java.awt.Dimension(600, 400));
        textField.setPreferredSize(new java.awt.Dimension(40, 26));
        add(textField);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel label;
    private javax.swing.JTextField textField;
    // End of variables declaration//GEN-END:variables

}
