
package view.components;

/**
 *
 * @author Sterbenxy13
 */
public class FrReadedBooks extends javax.swing.JDialog {
    private javax.swing.DefaultListModel<model.entity.Book> listModel;
    private controller.UserManager manager;
    private int userIndex;
    
    /**
     * Creates new form FrReadedBooks
     */
    public FrReadedBooks(java.awt.Dialog parent, boolean modal, java.util.List<model.entity.Book> books, controller.UserManager manager) {
        super(parent, modal);
        initComponents();
        this.userIndex = 0;
        this.manager = manager;
        listModel = new javax.swing.DefaultListModel<>();
        
        for (model.entity.Book b: books) {
            listModel.addElement(b);
        }
        lstBooks.setModel(listModel);   
    }
    
    public FrReadedBooks(java.awt.Dialog parent, boolean modal, int userIndex, controller.UserManager manager) {
        super(parent, modal);
        initComponents();
        this.userIndex = userIndex;
        this.manager = manager;
        listModel = new javax.swing.DefaultListModel<>();
        
        for (model.entity.Book b: manager.getReadedBooks(userIndex)) {
            System.out.println(b);
            listModel.addElement(b);
        }
        lstBooks.setModel(listModel);   
    }
    
    public java.util.List<model.entity.Book> getReadedBooksValue() {
        java.util.List<model.entity.Book> result = new java.util.ArrayList<>();
        for (int i = 0; i < this.listModel.size(); i ++) {
            result.add(listModel.getElementAt(i));
        }
        return result;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new view.components.LblTitle();
        lblAlert = new view.components.LblAlert();
        panBooks = new javax.swing.JScrollPane();
        lstBooks = new javax.swing.JList<>();
        panOptions = new javax.swing.JPanel();
        btnCancel = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitle.setText("Livros lidos");

        lstBooks.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        panBooks.setViewportView(lstBooks);

        btnCancel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnCancel.setText("Voltar");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        panOptions.add(btnCancel);

        btnAdd.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnAdd.setText("Adicionar");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        panOptions.add(btnAdd);

        btnRemove.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnRemove.setText("Remover");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });
        panOptions.add(btnRemove);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAlert, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panBooks, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addComponent(panOptions, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAlert, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panBooks, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panOptions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        lblAlert.setText("");
        
        controller.BookManager bookManager
                = new controller.BookManager();
        
        view.components.FrSelect edtBook
                = new view.components.FrSelect(this, true, bookManager);
        edtBook.setVisible(true);
        
        if (!edtBook.wasSelected()) {
            return;
        }
        
        view.components.DlgTextInput edtGrade
                = new view.components.DlgTextInput(this, true, "Insira sua nota de 0 a 5 para o livro");
        edtGrade.setVisible(true);
        
        int grade;
        while (true) {
            try {
                grade = Integer.parseInt(edtGrade.getValue());
                if (grade < 0 || grade > 5) {
                    new view.components.DlgAlert(this, true, "A nota deve ser entre 0 e 5!");
                    edtGrade.setVisible(true);
                    continue;
                }
                break;
            } catch (Exception e) {
                new view.components.DlgAlert(this, true, "A nota deve ser um número!");
                edtGrade.setVisible(true);
            }
        }
        
        String tempData = bookManager.getJsonData(edtBook.getEdtIndexValue());
        model.entity.Book temp = model.persistence.JSONService.fromJson(tempData, model.entity.Book.class).get(0);
        bookManager.addGrade(edtBook.getEdtIndexValue(), grade);
        this.manager.addReadedBook(this.userIndex, temp, grade);
        listModel.addElement(temp);
        lstBooks.setModel(listModel);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        if (lstBooks.getSelectedIndex() != -1) {
            listModel.remove(lstBooks.getSelectedIndex());
            lblAlert.setText("Removido com sucesso!");
        } else {
            lblAlert.setText("Selecione um item para remover!");
        }
    }//GEN-LAST:event_btnRemoveActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnRemove;
    private view.components.LblAlert lblAlert;
    private view.components.LblTitle lblTitle;
    private javax.swing.JList<model.entity.Book> lstBooks;
    private javax.swing.JScrollPane panBooks;
    private javax.swing.JPanel panOptions;
    // End of variables declaration//GEN-END:variables
}
