
package view.components;

/**
 *
 * @author Sterbenxy13
 */
public class FrSelect extends javax.swing.JDialog {
    private controller.IEntityController manager;
    private boolean selected = false;
    
    /**
     * Creates new form FrSelect
     */
    public FrSelect(java.awt.Frame parent, boolean modal, controller.IEntityController manager) {
        super(parent, modal);
        initComponents();
        this.manager = manager;
        
        edtIndex.setModel(new javax.swing.SpinnerNumberModel(
                0, 
                0, 
                manager.getSize() - 1,
                1
            )
        );
        
        this.updateData();
    }
    
    public FrSelect(java.awt.Dialog parent, boolean modal, controller.IEntityController manager) {
        super(parent, modal);
        initComponents();
        this.manager = manager;
        
        edtIndex.setModel(new javax.swing.SpinnerNumberModel(
                0, 
                0, 
                manager.getSize() - 1,
                1
            )
        );
        
        this.updateData();
    }
    
    public boolean wasSelected() {
        return this.selected;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panDadosPessoa = new javax.swing.JScrollPane();
        edtDadosPessoa = new javax.swing.JTextArea();
        panIndex = new javax.swing.JPanel();
        lblIndex = new javax.swing.JLabel();
        edtIndex = new javax.swing.JSpinner();
        panOptions = new javax.swing.JPanel();
        btnCancel = new javax.swing.JButton();
        btnConfirm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        edtDadosPessoa.setEditable(false);
        edtDadosPessoa.setColumns(20);
        edtDadosPessoa.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        edtDadosPessoa.setRows(5);
        panDadosPessoa.setViewportView(edtDadosPessoa);

        panIndex.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING, 30, 5));

        lblIndex.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblIndex.setText("ID:");
        panIndex.add(lblIndex);

        edtIndex.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        edtIndex.setMinimumSize(new java.awt.Dimension(100, 20));
        edtIndex.setPreferredSize(new java.awt.Dimension(100, 20));
        edtIndex.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                edtIndexStateChanged(evt);
            }
        });
        panIndex.add(edtIndex);

        panOptions.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 10));

        btnCancel.setText("Cancelar");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        panOptions.add(btnCancel);

        btnConfirm.setText("Selecionar");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });
        panOptions.add(btnConfirm);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panOptions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panIndex, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addComponent(panDadosPessoa, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(panIndex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panDadosPessoa, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void edtIndexStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_edtIndexStateChanged
        this.updateData();
    }//GEN-LAST:event_edtIndexStateChanged

    private void updateData() {
        edtDadosPessoa.setText(
            manager.getFormattedData(getEdtIndexValue())
        );
    }
    
    public int getEdtIndexValue(){
        return Integer.parseInt(edtIndex.getValue().toString());
    }
    
    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        this.selected = true;
        this.dispose();
    }//GEN-LAST:event_btnConfirmActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JTextArea edtDadosPessoa;
    private javax.swing.JSpinner edtIndex;
    private javax.swing.JLabel lblIndex;
    private javax.swing.JScrollPane panDadosPessoa;
    private javax.swing.JPanel panIndex;
    private javax.swing.JPanel panOptions;
    // End of variables declaration//GEN-END:variables
}
