
package view.components;

/**
 *
 * @author Sterbenxy13
 */
public class PanData extends javax.swing.JPanel {
    private controller.IEntityController manager;
    
    public PanData() {
        initComponents();
    }
    
    public PanData(controller.IEntityController manager) {
        initComponents();
        this.manager = manager;
        this.updateData();
    }
    
    public PanData(controller.IEntityController manager, int index) {
        initComponents();
        this.manager = manager;
        this.updateData(index);
    }
    
    public void setManager(controller.IEntityController manager) {
        this.manager = manager;
    }
    
    public boolean isEmpty() {
        return this.edtData.getText().equals("");
    }
    
    public void updateData() {
        this.edtData.setText(manager.getFormattedData());   
    }
    
    public void updateData(int index) {
        this.edtData.setText(manager.getFormattedData(index));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        edtData = new javax.swing.JTextArea();

        setEnabled(false);

        edtData.setEditable(false);
        edtData.setColumns(20);
        edtData.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        edtData.setRows(5);
        jScrollPane1.setViewportView(edtData);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea edtData;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
